# The name of the workflow
name: UpdateSchedule

# The trigger for the workflow
on:
  schedule:
    # Run the workflow on a schedule (using a cron expression)
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs in the workflow.
jobs:
  update:
    # Specify the environment in which the job should run
    runs-on: ubuntu-latest
    
    # Set an environment variable GitHub token for the job
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    # The steps of the job
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Set up R in the environment
      - uses: r-lib/actions/setup-r@v2
        with:
          # Use the public R package repository
          use-public-rspm: true
          
      # Install dependencies    
      - name: Install dependencies
        run: |
          install.packages(c("magrittr","dplyr", "lubridate", "TeachingDemos"))
        shell: Rscript {0}
      
      # Update data  
      - name: Update data
        run: |
          source('code/generate_ics.R'); source('code/generateSchedule.R')
        shell: Rscript {0}
      
      # Commit and push changes to the repository
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if git status --porcelain | grep -q "^ M"; then
              git add .
              git commit -am "add data"
              git push
          else
              echo "No changes to commit"
          fi
